// <auto-generated />
using System;
using HotelOazis.Models.DbConfiguration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelOazis.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20250312205039_seedByRelativePath")]
    partial class seedByRelativePath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelOazis.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2947acfc-ba5c-409d-b23c-ad23e216c6a3"),
                            CheckInDate = new DateTime(2025, 3, 18, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4281),
                            CheckOutDate = new DateTime(2025, 3, 26, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4292),
                            RoomId = new Guid("f32b8731-9a32-4166-bd9c-ce87b0f751f1"),
                            UserId = new Guid("62e49715-f9c3-4cfa-8684-e4ef56553bd1")
                        },
                        new
                        {
                            Id = new Guid("fd4afc8c-5895-459d-b05c-286aaceabc0c"),
                            CheckInDate = new DateTime(2025, 3, 20, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4298),
                            CheckOutDate = new DateTime(2025, 3, 26, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4299),
                            RoomId = new Guid("8fd80935-2588-4422-9846-7e7f847e7f46"),
                            UserId = new Guid("62e49715-f9c3-4cfa-8684-e4ef56553bd1")
                        },
                        new
                        {
                            Id = new Guid("a29087b5-5013-4ba9-83c7-5f29406783bc"),
                            CheckInDate = new DateTime(2025, 3, 15, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4301),
                            CheckOutDate = new DateTime(2025, 3, 26, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4302),
                            RoomId = new Guid("a4d9e735-1f9c-4bcf-994d-fdb933f4b1bd"),
                            UserId = new Guid("ab7438cf-2d2e-4ca8-a0fe-a8de9ce87232")
                        },
                        new
                        {
                            Id = new Guid("bb378855-43de-4232-ac81-389701f963ad"),
                            CheckInDate = new DateTime(2025, 3, 15, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4304),
                            CheckOutDate = new DateTime(2025, 3, 27, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4304),
                            RoomId = new Guid("c3d8ff66-b605-4752-a641-5ffe16bef122"),
                            UserId = new Guid("ab7438cf-2d2e-4ca8-a0fe-a8de9ce87232")
                        },
                        new
                        {
                            Id = new Guid("fc20368d-6bc9-4aa4-904d-141fee12a0ab"),
                            CheckInDate = new DateTime(2025, 3, 16, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4306),
                            CheckOutDate = new DateTime(2025, 3, 27, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4307),
                            RoomId = new Guid("d2258c92-e082-4703-9d09-c6fbe3e60560"),
                            UserId = new Guid("a620c127-8fdf-4b0e-b2e7-14d6f7bc0542")
                        },
                        new
                        {
                            Id = new Guid("d0589d88-10ff-4468-b92c-b12f95f89104"),
                            CheckInDate = new DateTime(2025, 3, 19, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4310),
                            CheckOutDate = new DateTime(2025, 3, 27, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4310),
                            RoomId = new Guid("a610b314-c5ab-42eb-b9eb-82285e28fda0"),
                            UserId = new Guid("a620c127-8fdf-4b0e-b2e7-14d6f7bc0542")
                        },
                        new
                        {
                            Id = new Guid("208123a6-d362-4c38-ae1d-5204de092dd1"),
                            CheckInDate = new DateTime(2025, 3, 19, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4312),
                            CheckOutDate = new DateTime(2025, 3, 27, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4312),
                            RoomId = new Guid("b34b8faf-902e-48a4-8c57-71d60bf8effe"),
                            UserId = new Guid("89fd0f00-7a3e-4649-a3ad-ed4a21da66ba")
                        },
                        new
                        {
                            Id = new Guid("1a347187-74b8-40d2-833c-0d55cd126f8a"),
                            CheckInDate = new DateTime(2025, 3, 14, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4314),
                            CheckOutDate = new DateTime(2025, 3, 24, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4315),
                            RoomId = new Guid("7485521e-126d-4044-bb34-7a98c36f5e27"),
                            UserId = new Guid("89fd0f00-7a3e-4649-a3ad-ed4a21da66ba")
                        },
                        new
                        {
                            Id = new Guid("bf78e66c-9fc3-45fb-b5fd-1b67e9aa3e9b"),
                            CheckInDate = new DateTime(2025, 3, 18, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4320),
                            CheckOutDate = new DateTime(2025, 3, 30, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4320),
                            RoomId = new Guid("e382d7d8-4350-46cb-82d5-1350c1dcbb47"),
                            UserId = new Guid("7ae8b066-2a15-488f-9045-3d895bce6a01")
                        },
                        new
                        {
                            Id = new Guid("6eed5880-db6a-4854-b195-6f0419509efa"),
                            CheckInDate = new DateTime(2025, 3, 17, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4323),
                            CheckOutDate = new DateTime(2025, 3, 29, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4323),
                            RoomId = new Guid("6035eec3-f804-4d98-ad45-9e55516bc0c2"),
                            UserId = new Guid("7ae8b066-2a15-488f-9045-3d895bce6a01")
                        });
                });

            modelBuilder.Entity("HotelOazis.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MessageStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fdfeac9f-a884-4ce5-b4f1-c96a19e5d084"),
                            Message = "Amazing stay! AliceSmith had a wonderful experience.",
                            MessageStatus = 0,
                            PublishedOn = new DateTime(2025, 3, 12, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4387),
                            Rating = 4,
                            UserId = new Guid("62e49715-f9c3-4cfa-8684-e4ef56553bd1")
                        },
                        new
                        {
                            Id = new Guid("55636731-a94d-4258-9706-995f22686f56"),
                            Message = "Amazing stay! BobJohnson had a wonderful experience.",
                            MessageStatus = 0,
                            PublishedOn = new DateTime(2025, 3, 12, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4394),
                            Rating = 3,
                            UserId = new Guid("ab7438cf-2d2e-4ca8-a0fe-a8de9ce87232")
                        },
                        new
                        {
                            Id = new Guid("9dcc7619-bd84-4d80-a0a2-2c0293b5062c"),
                            Message = "Amazing stay! CharlieBrown had a wonderful experience.",
                            MessageStatus = 0,
                            PublishedOn = new DateTime(2025, 3, 12, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4397),
                            Rating = 3,
                            UserId = new Guid("a620c127-8fdf-4b0e-b2e7-14d6f7bc0542")
                        },
                        new
                        {
                            Id = new Guid("7ec6dd3c-5307-4fc0-b3d3-26ce1e233750"),
                            Message = "Amazing stay! DianaWhite had a wonderful experience.",
                            MessageStatus = 0,
                            PublishedOn = new DateTime(2025, 3, 12, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4400),
                            Rating = 5,
                            UserId = new Guid("89fd0f00-7a3e-4649-a3ad-ed4a21da66ba")
                        },
                        new
                        {
                            Id = new Guid("e9a81dea-35c0-4ef9-88e8-418a6f05c456"),
                            Message = "Amazing stay! EdwardBlack had a wonderful experience.",
                            MessageStatus = 0,
                            PublishedOn = new DateTime(2025, 3, 12, 20, 50, 38, 458, DateTimeKind.Utc).AddTicks(4402),
                            Rating = 3,
                            UserId = new Guid("7ae8b066-2a15-488f-9045-3d895bce6a01")
                        });
                });

            modelBuilder.Entity("HotelOazis.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HotelOazis.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f32b8731-9a32-4166-bd9c-ce87b0f751f1"),
                            Description = "Cozy single room with a city view.",
                            IsAvailable = true,
                            Number = 101,
                            Picture = "C:\\Users\\mitko\\source\\repos\\HotelOazis\\HotelOazis\\bin\\Debug\\net8.0-windows\\Resources\\singleRoom1.jpg",
                            Price = 80.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("8fd80935-2588-4422-9846-7e7f847e7f46"),
                            Description = "Spacious double room with modern amenities.",
                            IsAvailable = true,
                            Number = 102,
                            Picture = "C:\\Users\\mitko\\source\\repos\\HotelOazis\\HotelOazis\\bin\\Debug\\net8.0-windows\\Resources\\doubleRoom.jpg",
                            Price = 120.00m,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("a4d9e735-1f9c-4bcf-994d-fdb933f4b1bd"),
                            Description = "Luxury suite with a king-sized bed and ocean view.",
                            IsAvailable = true,
                            Number = 103,
                            Picture = "C:\\Users\\mitko\\source\\repos\\HotelOazis\\HotelOazis\\bin\\Debug\\net8.0-windows\\Resources\\tripleRoom1.jpg",
                            Price = 200.00m,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("c3d8ff66-b605-4752-a641-5ffe16bef122"),
                            Description = "Comfortable single room with free Wi-Fi.",
                            IsAvailable = true,
                            Number = 104,
                            Picture = "C:\\Users\\mitko\\source\\repos\\HotelOazis\\HotelOazis\\bin\\Debug\\net8.0-windows\\Resources\\singleRoom2.jpg",
                            Price = 75.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("d2258c92-e082-4703-9d09-c6fbe3e60560"),
                            Description = "Elegant double room with a balcony.",
                            IsAvailable = true,
                            Number = 105,
                            Picture = "C:\\Users\\mitko\\source\\repos\\HotelOazis\\HotelOazis\\bin\\Debug\\net8.0-windows\\Resources\\doubleRoom2.jpg",
                            Price = 130.00m,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("a610b314-c5ab-42eb-b9eb-82285e28fda0"),
                            Description = "Premium suite with a private hot tub.",
                            IsAvailable = true,
                            Number = 106,
                            Picture = "C:\\Users\\mitko\\source\\repos\\HotelOazis\\HotelOazis\\bin\\Debug\\net8.0-windows\\Resources\\quadRoom.jpg",
                            Price = 220.00m,
                            Type = 4
                        },
                        new
                        {
                            Id = new Guid("b34b8faf-902e-48a4-8c57-71d60bf8effe"),
                            Description = "Modern single room with a work desk.",
                            IsAvailable = true,
                            Number = 107,
                            Picture = "C:\\Users\\mitko\\source\\repos\\HotelOazis\\HotelOazis\\bin\\Debug\\net8.0-windows\\Resources\\singleRoom3.jpg",
                            Price = 85.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("7485521e-126d-4044-bb34-7a98c36f5e27"),
                            Description = "Stylish double room with a city skyline view.",
                            IsAvailable = true,
                            Number = 108,
                            Picture = "C:\\Users\\mitko\\source\\repos\\HotelOazis\\HotelOazis\\bin\\Debug\\net8.0-windows\\Resources\\doubleRoom3.jpg",
                            Price = 140.00m,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("e382d7d8-4350-46cb-82d5-1350c1dcbb47"),
                            Description = "Exclusive suite with a private lounge area.",
                            IsAvailable = true,
                            Number = 109,
                            Picture = "C:\\Users\\mitko\\source\\repos\\HotelOazis\\HotelOazis\\bin\\Debug\\net8.0-windows\\Resources\\familyRoom.jpg",
                            Price = 250.00m,
                            Type = 5
                        },
                        new
                        {
                            Id = new Guid("6035eec3-f804-4d98-ad45-9e55516bc0c2"),
                            Description = "Charming double room with artistic decor.",
                            IsAvailable = true,
                            Number = 110,
                            Picture = "C:\\Users\\mitko\\source\\repos\\HotelOazis\\HotelOazis\\bin\\Debug\\net8.0-windows\\Resources\\doubleRoom4.jpg",
                            Price = 135.00m,
                            Type = 2
                        });
                });

            modelBuilder.Entity("HotelOazis.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66b94d19-c295-4f74-809e-8be2759867e0"),
                            Description = "Relaxing full-body spa experience.",
                            Name = "Spa Treatment"
                        },
                        new
                        {
                            Id = new Guid("b373b4e9-9ffa-43a4-b7d7-54f1bfb68d69"),
                            Description = "Unlimited access to our state-of-the-art fitness center.",
                            Name = "Gym Access"
                        },
                        new
                        {
                            Id = new Guid("48aacee4-3887-4440-9c39-c1d768d1d695"),
                            Description = "Convenient transport to and from the airport.",
                            Name = "Airport Shuttle"
                        },
                        new
                        {
                            Id = new Guid("16506d12-fc37-4146-b837-910b942bb287"),
                            Description = "Delicious breakfast with a variety of options.",
                            Name = "Breakfast Buffet"
                        },
                        new
                        {
                            Id = new Guid("f027d1f3-2587-49d5-8728-024181f152c3"),
                            Description = "24/7 room service with gourmet meals.",
                            Name = "Room Service"
                        },
                        new
                        {
                            Id = new Guid("8bf4edfe-a162-4c68-9c9c-e9c5183ff3de"),
                            Description = "Same-day laundry and dry-cleaning services.",
                            Name = "Laundry Service"
                        },
                        new
                        {
                            Id = new Guid("91a85990-a7d9-4665-989a-68f7bab57908"),
                            Description = "Guided tour of local attractions.",
                            Name = "City Tour"
                        },
                        new
                        {
                            Id = new Guid("6d008672-1bf1-42cf-ade3-11810d1e168f"),
                            Description = "High-speed internet available in all areas.",
                            Name = "Wi-Fi Access"
                        },
                        new
                        {
                            Id = new Guid("7a183520-3bc4-4680-979c-1314b4ba0431"),
                            Description = "Fully equipped meeting and conference facilities.",
                            Name = "Conference Room"
                        },
                        new
                        {
                            Id = new Guid("e53fe1b4-138b-40e9-8645-cb4f7fd7580b"),
                            Description = "Access to our indoor heated pool.",
                            Name = "Swimming Pool"
                        });
                });

            modelBuilder.Entity("HotelOazis.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("62e49715-f9c3-4cfa-8684-e4ef56553bd1"),
                            Age = 28,
                            AvatarUrl = "C:\\Users\\mitko\\source\\repos\\HotelOazis\\HotelOazis\\bin\\Debug\\net8.0-windows\\Resources\\womanAvatar.jpg",
                            Email = "alice@example.com",
                            Password = "hashedpassword",
                            Username = "AliceSmith"
                        },
                        new
                        {
                            Id = new Guid("ab7438cf-2d2e-4ca8-a0fe-a8de9ce87232"),
                            Age = 35,
                            AvatarUrl = "C:\\Users\\mitko\\source\\repos\\HotelOazis\\HotelOazis\\bin\\Debug\\net8.0-windows\\Resources\\manAvatar.jpg",
                            Email = "bob@example.com",
                            Password = "hashedpassword",
                            Username = "BobJohnson"
                        },
                        new
                        {
                            Id = new Guid("a620c127-8fdf-4b0e-b2e7-14d6f7bc0542"),
                            Age = 40,
                            AvatarUrl = "C:\\Users\\mitko\\source\\repos\\HotelOazis\\HotelOazis\\bin\\Debug\\net8.0-windows\\Resources\\womanAvatar.jpg",
                            Email = "charlie@example.com",
                            Password = "hashedpassword",
                            Username = "CharlieBrown"
                        },
                        new
                        {
                            Id = new Guid("89fd0f00-7a3e-4649-a3ad-ed4a21da66ba"),
                            Age = 30,
                            AvatarUrl = "C:\\Users\\mitko\\source\\repos\\HotelOazis\\HotelOazis\\bin\\Debug\\net8.0-windows\\Resources\\womanAvatar.jpg",
                            Email = "diana@example.com",
                            Password = "hashedpassword",
                            Username = "DianaWhite"
                        },
                        new
                        {
                            Id = new Guid("7ae8b066-2a15-488f-9045-3d895bce6a01"),
                            Age = 33,
                            AvatarUrl = "C:\\Users\\mitko\\source\\repos\\HotelOazis\\HotelOazis\\bin\\Debug\\net8.0-windows\\Resources\\manAvatar.jpg",
                            Email = "edward@example.com",
                            Password = "hashedpassword",
                            Username = "EdwardBlack"
                        });
                });

            modelBuilder.Entity("HotelOazis.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsersRoles");
                });

            modelBuilder.Entity("HotelOazis.Models.Reservation", b =>
                {
                    b.HasOne("HotelOazis.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelOazis.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelOazis.Models.Review", b =>
                {
                    b.HasOne("HotelOazis.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelOazis.Models.UserRole", b =>
                {
                    b.HasOne("HotelOazis.Models.Role", "Role")
                        .WithMany("RolesUsers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelOazis.Models.User", "User")
                        .WithMany("UsersRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelOazis.Models.Role", b =>
                {
                    b.Navigation("RolesUsers");
                });

            modelBuilder.Entity("HotelOazis.Models.User", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Reviews");

                    b.Navigation("UsersRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
